#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem=100g
#SBATCH --time=12:00:00
#SBATCH --job-name=genome_index
#SBATCH --output=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxsc9@nottingham.ac.uk

#Activates the conda environment
source $HOME/.bash_profile
conda activate rotation2

STAR \
--runThreadN 32 \
--runMode genomeGenerate \
--genomeDir /share/BioinfMSc/life4136_2526/rotation2/group4/HSapiens/HSapiens_reference/GRCh38_index \
--genomeFastaFiles /share/BioinfMSc/life4136_2526/rotation2/group4/HSapiens/HSapiens_reference/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa \
--sjdbGTFfile /share/BioinfMSc/life4136_2526/rotation2/group4/HSapiens/HSapiens_reference/Homo_sapiens.GRCh38.115.gtf \
--sjdbOverhang 100

conda deactivate
